import type { GlossaryTerm } from "./types";

// Alphabetized reference of every domain term used across the app and guides.
export const GLOSSARY: GlossaryTerm[] = [
  {
    term: "Action potential",
    definition:
      "A rapid, all-or-nothing electrical spike a neuron emits when its membrane potential crosses threshold. In CortexSim this is the moment v reaches +30 mV and is reset.",
    related: ["Membrane potential", "Threshold"],
  },
  {
    term: "Adaptation",
    definition:
      "The tendency of a neuron to slow its firing during sustained input, modeled by the recovery variable u and the reset parameter d.",
    related: ["Recovery variable", "Izhikevich model"],
  },
  {
    term: "Balanced state",
    definition:
      "A regime in which excitatory and inhibitory currents roughly cancel, producing irregular, low-rate firing that responds quickly and linearly to input. The healthy resting mode of cortex.",
    related: ["Excitation", "Inhibition"],
  },
  {
    term: "Connectivity",
    definition:
      "The probability (or density) that any two neurons are connected. Higher connectivity increases interaction strength and computational cost.",
    related: ["Topology"],
  },
  {
    term: "Conduction delay",
    definition:
      "The time a spike takes to travel from one neuron to another, often scaled by distance. Delays enable traveling waves and polychronous groups.",
    related: ["Polychronization", "Traveling wave"],
  },
  {
    term: "Correlation matrix",
    definition:
      "A grid of pairwise Pearson correlations between neurons' binned activity. Bright off-diagonal blocks reveal co-firing assemblies.",
    related: ["Synchrony", "Assembly"],
  },
  {
    term: "Entropy",
    definition:
      "A measure of unpredictability in the population's activity distribution. Often peaks in the balanced regime where the network carries the most information.",
  },
  {
    term: "Excitation",
    definition:
      "Synaptic input that pushes a neuron's membrane potential toward threshold, increasing its chance of firing. About 80% of cortical neurons are excitatory.",
    related: ["Inhibition", "Balanced state"],
  },
  {
    term: "FFT",
    definition:
      "Fast Fourier Transform - an efficient algorithm that decomposes a time signal into its constituent frequencies. The basis of the power spectrum.",
    related: ["Welch's method", "Power spectrum"],
  },
  {
    term: "Gamma rhythm",
    definition:
      "Oscillations in the 30-80+ Hz band linked to attention and local processing, commonly generated by fast inhibitory feedback (PING).",
    related: ["Power spectrum", "Inhibition"],
  },
  {
    term: "Inhibition",
    definition:
      "Synaptic input that pulls a neuron away from threshold, reducing firing. Carried by fast-spiking interneurons and essential for stability and rhythms.",
    related: ["Excitation", "Balanced state"],
  },
  {
    term: "Izhikevich model",
    definition:
      "A two-variable spiking neuron model that is computationally cheap yet reproduces many biological firing patterns. The core of CortexSim's engine.",
    related: ["Membrane potential", "Recovery variable"],
  },
  {
    term: "LFP",
    definition:
      "Local field potential - a summed measure of nearby neural activity. CortexSim approximates it with the population firing-rate signal.",
  },
  {
    term: "Membrane potential",
    definition:
      "The voltage across a neuron's membrane, written v. It rises with excitatory input and triggers a spike at threshold.",
    related: ["Action potential"],
  },
  {
    term: "Polychronization",
    definition:
      "The emergence of reproducible, time-locked firing sequences among neurons with matched conduction delays. Proposed as a memory substrate.",
    related: ["Conduction delay", "STDP"],
  },
  {
    term: "Power spectrum",
    definition:
      "A plot of signal power against frequency, revealing which rhythms dominate the network's activity.",
    related: ["FFT", "Welch's method"],
  },
  {
    term: "Raster plot",
    definition:
      "A scatter of spikes with neuron index on the vertical axis and time on the horizontal axis. The most information-dense view of network activity.",
  },
  {
    term: "Recovery variable",
    definition:
      "The second Izhikevich state variable, u, abstracting slow ionic currents that pull a neuron back toward rest after firing.",
    related: ["Izhikevich model", "Adaptation"],
  },
  {
    term: "STDP",
    definition:
      "Spike-timing-dependent plasticity - a learning rule that strengthens synapses when the presynaptic spike precedes the postsynaptic one and weakens them otherwise.",
    related: ["Polychronization"],
  },
  {
    term: "Synchrony",
    definition:
      "The degree to which neurons fire together. Ranges from 0 (independent) to 1 (locked in lockstep).",
    related: ["Correlation matrix"],
  },
  {
    term: "Topology",
    definition:
      "The pattern of connections between neurons: random, small-world, scale-free or grid. Strongly shapes the dynamics.",
    related: ["Connectivity"],
  },
  {
    term: "Traveling wave",
    definition:
      "A spatial pattern in which activity sweeps across the network over time, visible as diagonal streaks in the raster. Requires delays and spatial structure.",
    related: ["Conduction delay", "Topology"],
  },
  {
    term: "Welch's method",
    definition:
      "A spectral estimation technique that averages the spectra of overlapping windowed segments to produce a smooth, reliable power spectrum.",
    related: ["FFT", "Power spectrum"],
  },
];
