// The full platform capability catalog, derived from the CortexSim Advanced
// specification (35 sections). Each entry documents what the section does, a
// practical tip, and the outcome a user gets. "status" is honest about what is
// live in this build versus on the roadmap, so the catalog doubles as a map of
// the platform.

export type SectionStatus = "live" | "beta" | "roadmap";

export interface SectionSpec {
  id: number;
  title: string;
  group: string;
  what: string;
  tip: string;
  outcome: string;
  status: SectionStatus;
}

export const SECTION_GROUPS = [
  "Visualization",
  "Analysis",
  "Dynamics & Learning",
  "Connectivity",
  "Performance & Systems",
  "Data & Protocols",
] as const;

export const SECTIONS: SectionSpec[] = [
  {
    id: 1,
    title: "Real-time performance dashboard",
    group: "Performance & Systems",
    what: "Live FPS, compute-vs-wall-clock factor, frame timing and memory pressure for the simulation loop.",
    tip: "Cap the frame rate to save battery on laptops without changing the science.",
    outcome: "You always know whether your device, not the model, is the bottleneck.",
    status: "live",
  },
  {
    id: 2,
    title: "Parameter space explorer",
    group: "Dynamics & Learning",
    what: "Grid and random sweeps over any parameter, plotted as a curve or heatmap of a target metric.",
    tip: "Keep the network small during sweeps so each point finishes fast.",
    outcome: "You find the parameter region that produces the behavior you want.",
    status: "live",
  },
  {
    id: 3,
    title: "Dynamic clamp & input injector",
    group: "Dynamics & Learning",
    what: "Inject sine, pulse, ramp, noise or custom-expression current into selected neurons or the whole population.",
    tip: "Press I to fire a quick pulse and watch the network's impulse response.",
    outcome: "You probe how the network reacts to controlled stimulation.",
    status: "live",
  },
  {
    id: 4,
    title: "Enhanced spike raster",
    group: "Visualization",
    what: "Spikes by neuron and time, colored by excitatory / inhibitory type, with a rolling window.",
    tip: "Speckle = asynchronous, vertical bands = synchronized, diagonals = waves.",
    outcome: "You diagnose network state at a single glance.",
    status: "live",
  },
  {
    id: 5,
    title: "Population firing rate",
    group: "Visualization",
    what: "Excitatory, inhibitory and total population rates over time with smoothing.",
    tip: "Watch E and I traces lag each other - that lag drives many rhythms.",
    outcome: "You see the heartbeat of the whole network.",
    status: "live",
  },
  {
    id: 6,
    title: "LFP spectrogram",
    group: "Analysis",
    what: "Time-frequency view (0-150 Hz) of the local field potential as it evolves.",
    tip: "Use it to catch transient bursts of gamma that a static spectrum misses.",
    outcome: "You track how rhythms appear and vanish over time.",
    status: "roadmap",
  },
  {
    id: 7,
    title: "Cross-correlation & coherence",
    group: "Analysis",
    what: "Cross-correlograms and phase-locking between neuron groups or spikes and LFP.",
    tip: "Compare two populations to reveal who leads and who follows.",
    outcome: "You quantify directed coordination between regions.",
    status: "roadmap",
  },
  {
    id: 8,
    title: "Synchrony metrics panel",
    group: "Analysis",
    what: "Kuramoto order parameter, ISI-based synchrony and burst synchrony as live gauges.",
    tip: "Synchrony near 1 means the population is firing in lockstep.",
    outcome: "You measure coordination instead of guessing it.",
    status: "live",
  },
  {
    id: 9,
    title: "Information dynamics toolbox",
    group: "Analysis",
    what: "Transfer entropy and mutual information between populations or with the stimulus.",
    tip: "Use sliding windows to see information flow change over time.",
    outcome: "You measure how information moves through the network.",
    status: "roadmap",
  },
  {
    id: 10,
    title: "Phase plane (single neuron)",
    group: "Visualization",
    what: "Nullclines and the live (v, u) trajectory of a probed neuron.",
    tip: "Drag to set initial conditions and watch the trajectory evolve.",
    outcome: "You build deep intuition for single-neuron dynamics.",
    status: "live",
  },
  {
    id: 11,
    title: "Bifurcation diagram explorer",
    group: "Dynamics & Learning",
    what: "Sweep a parameter and plot the qualitative change in firing pattern.",
    tip: "Look for sudden jumps - those are bifurcations between regimes.",
    outcome: "You map the boundaries between network behaviors.",
    status: "roadmap",
  },
  {
    id: 12,
    title: "Connectivity matrix viewer & editor",
    group: "Connectivity",
    what: "Visualize the weight matrix and graph metrics; add, remove or rescale connections.",
    tip: "Check clustering and path length to confirm a small-world network.",
    outcome: "You inspect and sculpt the connectome directly.",
    status: "beta",
  },
  {
    id: 13,
    title: "STDP learning curve visualiser",
    group: "Dynamics & Learning",
    what: "Weight change over time for a sample synapse and the active STDP window.",
    tip: "Lower the learning rate if weights run away.",
    outcome: "You watch the network learn in real time.",
    status: "live",
  },
  {
    id: 14,
    title: "Homeostatic scaling panel",
    group: "Dynamics & Learning",
    what: "Track per-neuron rate and multiplicatively scale synapses toward a target rate.",
    tip: "Set a gentle time constant so scaling does not fight fast dynamics.",
    outcome: "You keep a plastic network stable over long runs.",
    status: "roadmap",
  },
  {
    id: 15,
    title: "Gap junctions & electrical coupling",
    group: "Connectivity",
    what: "Add electrical synapses between neurons and measure the synchrony change.",
    tip: "Electrical coupling synchronizes fast - add it sparingly.",
    outcome: "You explore a second, faster route to synchrony.",
    status: "roadmap",
  },
  {
    id: 16,
    title: "Multi-compartment neuron inspector",
    group: "Visualization",
    what: "Dendritic and somatic voltage plus calcium for a simple two-compartment cell.",
    tip: "Compare soma and dendrite traces to see signal propagation.",
    outcome: "You see beyond the point-neuron abstraction.",
    status: "roadmap",
  },
  {
    id: 17,
    title: "Burst analysis & detection",
    group: "Analysis",
    what: "Automatic burst detection with duration, inter-burst interval and intraburst frequency.",
    tip: "Use the IB excitatory model to generate clear bursts to detect.",
    outcome: "You quantify bursting rather than just seeing it.",
    status: "beta",
  },
  {
    id: 18,
    title: "Real-time scheduler settings",
    group: "Performance & Systems",
    what: "Simulation priority, max frame rate, and the simulation-vs-wall-clock offset.",
    tip: "Background priority lets the UI stay smooth during heavy sweeps.",
    outcome: "You trade speed for responsiveness on demand.",
    status: "beta",
  },
  {
    id: 19,
    title: "Distributed simulation manager",
    group: "Performance & Systems",
    what: "Split the network into partitions and visualize communication overhead and load balance.",
    tip: "A demonstration of how real neural simulators scale across cores.",
    outcome: "You understand the cost of parallelizing a network.",
    status: "roadmap",
  },
  {
    id: 20,
    title: "Custom model editor",
    group: "Dynamics & Learning",
    what: "Type your own dv/dt and du/dt expressions and hot-reload them into the engine.",
    tip: "Math functions like sin, exp and tanh are available in expressions.",
    outcome: "You experiment with neuron models without writing code.",
    status: "live",
  },
  {
    id: 21,
    title: "Experimental protocol scheduler",
    group: "Data & Protocols",
    what: "Design timed stimulation sequences on a visual timeline and export them as JSON.",
    tip: "Script a pulse then an inhibition to test causal interactions.",
    outcome: "You run reproducible, scripted experiments.",
    status: "roadmap",
  },
  {
    id: 22,
    title: "Noise & stochasticity configuration",
    group: "Dynamics & Learning",
    what: "Ornstein-Uhlenbeck, white and colored noise applied to input, release or background.",
    tip: "Colored noise desynchronizes more naturally than white noise.",
    outcome: "You add realistic variability to your network.",
    status: "beta",
  },
  {
    id: 23,
    title: "Spike-triggered average",
    group: "Analysis",
    what: "Average input or LFP preceding a chosen neuron's spikes.",
    tip: "Reveals the drive that reliably makes a neuron fire.",
    outcome: "You uncover what causes a neuron to spike.",
    status: "roadmap",
  },
  {
    id: 24,
    title: "Dimensionality reduction",
    group: "Analysis",
    what: "Real-time PCA / t-SNE of population firing-rate vectors as a moving scatter.",
    tip: "Color points by time to see the activity trace a trajectory.",
    outcome: "You view high-dimensional activity in 2D.",
    status: "roadmap",
  },
  {
    id: 25,
    title: "Attractor landscape viewer",
    group: "Dynamics & Learning",
    what: "A mean-field landscape of activity showing fixed points and basins.",
    tip: "Useful for understanding up/down states and bistability.",
    outcome: "You see the network's stable states as a terrain.",
    status: "roadmap",
  },
  {
    id: 26,
    title: "E/I ratio controller",
    group: "Dynamics & Learning",
    what: "Live excitatory/inhibitory balance with a PI controller that targets a chosen ratio.",
    tip: "Let the controller hold balance while you change other parameters.",
    outcome: "You maintain a precise E/I balance automatically.",
    status: "beta",
  },
  {
    id: 27,
    title: "Synaptic kinetics editor",
    group: "Dynamics & Learning",
    what: "Independent AMPA / NMDA / GABA rise and decay times and their effect on PSP shape.",
    tip: "Faster inhibition sharpens gamma; slower inhibition lowers its frequency.",
    outcome: "You tune the synaptic basis of network rhythms.",
    status: "beta",
  },
  {
    id: 28,
    title: "Power spectrum + peak detection",
    group: "Analysis",
    what: "Welch power spectrum (0-120 Hz) with automatic gamma / beta / theta peak detection and history.",
    tip: "The Dominant Hz metric is just the largest detected peak.",
    outcome: "You read the frequency content of activity instantly.",
    status: "live",
  },
  {
    id: 29,
    title: "Functional connectivity matrix",
    group: "Connectivity",
    what: "Pairwise correlation between firing rates with clustering overlay and export.",
    tip: "Bright off-diagonal blocks are co-firing assemblies.",
    outcome: "You reveal the network's functional groups.",
    status: "live",
  },
  {
    id: 30,
    title: "Live equation & metric calculator",
    group: "Data & Protocols",
    what: "Compute custom metrics like E/I ratio or sync * rate, with scriptable alerts.",
    tip: "Set an alert to stop the run when synchrony exceeds a threshold.",
    outcome: "You define and watch exactly the quantities you care about.",
    status: "live",
  },
  {
    id: 31,
    title: "Data recorder & report generator",
    group: "Data & Protocols",
    what: "Schedule recording of metrics to CSV/JSON and generate a formatted PDF report.",
    tip: "Name every recording so your exports stay organized.",
    outcome: "You capture and share results in one click.",
    status: "live",
  },
  {
    id: 32,
    title: "Model zoo & preset manager",
    group: "Data & Protocols",
    what: "Network archetypes (gamma, bursting, up/down, seizure) plus saving and sharing presets.",
    tip: "Start from the closest preset, then tune one slider at a time.",
    outcome: "You reach any regime in a single click.",
    status: "live",
  },
  {
    id: 33,
    title: "Process monitor (desktop)",
    group: "Performance & Systems",
    what: "File handles, network activity and power impact in a desktop build.",
    tip: "Relevant only for an Electron packaging of the app.",
    outcome: "You see the OS-level footprint of a long simulation.",
    status: "roadmap",
  },
  {
    id: 34,
    title: "Phase-response curve",
    group: "Analysis",
    what: "Perturb at different phases and plot the resulting phase shift.",
    tip: "The PRC predicts whether neurons will synchronize.",
    outcome: "You characterize a neuron's response to timing.",
    status: "roadmap",
  },
  {
    id: 35,
    title: "Input-output transfer function",
    group: "Analysis",
    what: "Steady-state firing rate versus constant input current, with the linear range marked.",
    tip: "The slope is the gain; the flat parts are saturation.",
    outcome: "You measure how a neuron converts input to output.",
    status: "beta",
  },
];

export function sectionsByGroup(): Array<{ group: string; items: SectionSpec[] }> {
  return SECTION_GROUPS.map((group) => ({
    group,
    items: SECTIONS.filter((s) => s.group === group),
  })).filter((g) => g.items.length > 0);
}

export const SECTION_STATS = {
  total: SECTIONS.length,
  live: SECTIONS.filter((s) => s.status === "live").length,
  beta: SECTIONS.filter((s) => s.status === "beta").length,
  roadmap: SECTIONS.filter((s) => s.status === "roadmap").length,
};
