/**
 * codegen.js — Reproducibility: generate runnable Python (Brian2) and a JSON
 * spec from the current GUI configuration. Every experiment in the GUI can be
 * exported as code so results are reproducible outside the browser.
 */
export function toBrian2(config) {
  const c = config;
  const isLif = c.model === "lif";
  const eqs = isLif
    ? `dv/dt = (-(v - ${c.modelParams?.v_rest ?? -65}*mV) + R*I)/tau : volt (unless refractory)\nI : amp\nR = ${(80).toFixed(1)}*Mohm : ohm (constant)`
    : `dv/dt = (0.04*v**2/mV + 5*v + 140*mV - u + I*mV)/ms : volt\ndu/dt = a*(b*v - u)/ms : volt\nI : 1`;
  return `# Auto-generated by CortexSim Pro — reproducible Brian2 script
# pip install brian2
from brian2 import *

# ---- Parameters ----
N = ${c.N}
NE = int(N * ${c.excitatoryRatio})
NI = N - NE
p_conn = ${c.connectionProb}
J = ${c.J}            # excitatory weight
g = ${c.g}            # relative inhibitory strength
D = ${c.delay}*ms     # synaptic delay
tau = ${isLif ? 20 : 10}*ms
defaultclock.dt = ${c.dt}*ms
seed(${c.seed})

eqs = '''
${eqs}
'''

G = NeuronGroup(N, eqs, threshold='v > ${isLif ? "-50*mV" : "30*mV"}',
                reset='${isLif ? "v = -65*mV" : "v = c; u += d"}',
                refractory=${isLif ? "2*ms" : "0*ms"}, method='euler')

# External Poisson drive
P = PoissonInput(G, 'I', 1, ${c.inputRate}*Hz, weight=${c.inputWeight})

# Recurrent synapses (E and I)
SE = Synapses(G[:NE], G, on_pre='I += ${c.J}'); SE.connect(p=p_conn); SE.delay = D
SI = Synapses(G[NE:], G, on_pre='I -= ${(c.g * c.J).toFixed(3)}'); SI.connect(p=p_conn); SI.delay = D

mon = SpikeMonitor(G)
rate = PopulationRateMonitor(G)
run(1000*ms)

print('Mean rate:', mon.num_spikes / N / 1.0, 'Hz')
# plot(mon.t/ms, mon.i, '.k'); show()
`;
}

export function toJSONSpec(config, describe) {
  return JSON.stringify(
    { cortexsim_version: "1.0", network: describe, config },
    null,
    2
  );
}

/** A NetworkX snippet for connectome analysis of the exported graph. */
export function toNetworkX() {
  return `# Load an exported CortexSim edge list into NetworkX
import networkx as nx, json
spec = json.load(open('cortexsim_network.json'))
G = nx.gnp_random_graph(spec['network']['N'], spec['config']['connectionProb'], directed=True)
print('clustering', nx.average_clustering(G))
print('modularity-ready graph with', G.number_of_edges(), 'edges')
`;
}
